#ifndef __Properties_Gui__
#define __Properties_Gui__

/**
@file
Subclass of Properties, which is generated by wxFormBuilder.
*/

#include <Properties.h>
#include <iostream>
#include <wx/tooltip.h>
#include <wx/hyperlink.h>

#include <fctsys.h>
#include <pgm_base.h>
#include <kiway.h>
#include <gr_basic.h>
#include <class_drawpanel.h>
#include <confirm.h>
#include <class_sch_screen.h>
#include <wxEeschemaStruct.h>
#include <base_units.h>

#include <general.h>
#include <class_library.h>
#include <sch_component.h>
#include <dialog_helpers.h>
//// end generated include

/** Implementing Properties */
class Properties_Gui : public Properties
{
	private:
		friend class SCH_EDIT_FRAME;

    	SCH_EDIT_FRAME* m_Parent;
    	SCH_COMPONENT*  m_Cmp;
		// Handlers for Properties events.
		void CloseOnClick( wxCommandEvent& event );
		void OkOnClick( wxCommandEvent& event );
	public:
		/** Constructor */
		Properties_Gui( wxWindow* parent );
		//void SCH_EDIT_FRAME::EditProperties( SCH_COMPONENT* aComponent );
	//// end generated class members
	
};

#endif // __Properties_Gui__
